[package]
name = "xtask"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
newline-converter = { workspace = true }
progenitor = { workspace = true }
regex = { workspace = true }
rustfmt-wrapper = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }

[package.metadata.dist]
dist = false
