[package]
name = "trace-request"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
dropshot = { workspace = true }
http = { workspace = true }
proc-macro2 = "1"
quote = "1"
syn = { version = "2.0", features = ["full"] }
tracing = { workspace = true }