[package]
name = "rfd-api"
version = { workspace = true }
edition = { workspace = true }
repository = "https://github.com/oxidecomputer/rfd-api"

[features]
local-dev = ["v-api/local-dev"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true }
config = { workspace = true }
dropshot = { workspace = true }
dropshot-verified-body = { workspace = true, features = ["github"] }
hex = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true }
meilisearch-sdk = { workspace = true }
minijinja = { workspace = true }
newtype-uuid = { workspace = true }
octorust = { workspace = true, features = ["httpcache"] }
partial-struct = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
reqwest-tracing = { workspace = true }
resend-rs = { workspace = true }
rustls = { workspace = true }
rfd-data = { path = "../rfd-data" }
rfd-github = { path = "../rfd-github" }
rfd-model = { path = "../rfd-model", features = ["installer"] }
rsa = { workspace = true, features = ["sha2"] }
schemars = { workspace = true, features = ["chrono"] }
secrecy = { workspace = true, features = ["serde"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
slog = { workspace = true }
slog-async = { workspace = true }
strum = { workspace = true }
tap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
trace-request = { path = "../trace-request" }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-slog = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
uuid = { workspace = true, features = ["v4", "serde"]  }
v-api = { workspace = true }
v-model = { workspace = true }
v-api-permission-derive = { workspace = true }

[build-dependencies]
build-info = { path = "../build-info" }

[dev-dependencies]
async-trait = { workspace = true }
rfd-model = { path = "../rfd-model", features = ["mock"] }
rsa = { workspace = true, features = ["pem"] }

[package.metadata.dist]
targets = ["x86_64-unknown-linux-gnu"]
