[package]
name = "rfd-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { workspace = true }
rfd-model = { path = "../rfd-model" }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
