name: license-check

on:
  pull_request:
  push:
    branch:
      - main

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@c4b6b3195c028447a395aeec8053cae2d6cfd0b5
