name: Release rfd-api

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: >-
      github.event_name == 'push' ||
      github.event.label.name == 'release-test' ||
      contains(github.event.pull_request.labels.*.name, 'release-test')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Determine release tag
        id: tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "value=v0.0.0-pre+${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          else
            echo "value=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      # Do this first, to avoid racing with release.yml
      - name: Create GitHub Release
        uses: ncipollo/release-action@caacf56b56ba217c4eaf0a9deb59dbcdd12abfcd
        with:
          allowUpdates: true
          draft: ${{ github.event_name == 'pull_request' }}
          tag: ${{ steps.tag.outputs.value }}
          generateReleaseNotes: true
          prerelease: ${{ contains(steps.tag.outputs.value, '-pre') }}

      - run: |
          rustup toolchain install

      - name: Build Release Binary
        run: |
          cargo build --release --package rfd-api --no-default-features

      - name: Upload Release Artifact
        run: |
          gh release upload --clobber "${{ steps.tag.outputs.value }}" "target/release/rfd-api"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
